config/routes.rb
Hcs::Application.routes.draw do

  resources :notes

  resources :sessions do
    resources :notes
  end

  resources :clients do
    resources :sessions
  end

  resources :users

  get "users/new"

  match '/opening', :to => 'clients#opening'

  match '/signup', :to => 'users#new'

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/commonissues', :to => 'pages#commonissues'
  match '/barriers', :to => 'pages#barriers'
  match '/opening', :to => 'pages#opening'
  match '/positive', :to => 'pages#positive'
  match '/closing', :to => 'pages#closing'

  root :to => 'pages#home'

end

app/models/client.rb
class Client < ActiveRecord::Base 
  has_many :sessions
end





  

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  
  
  def opening
     @client = Client.find(params[:id])
    @title = "Opening"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end
  
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :ok }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
<% if @client.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

	<ul>
		<% @client.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :name %>
	<br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :name, 'Referral Date' %>
	<br />
	<%= f.date_select :referral_date, :referral_date => 2012 %>
</div>

<div class="field">
	<%= f.label :name, 'Enroll Date' %>
	<br />
	<%= f.date_select :enrolldate, :start_year => 2012 %>
</div>

<div class="field">
	<%= f.label :name, 'Date of Birth' %>
	<br />
	<%= f.date_select :dob, :start_year => 1920 %>
</div>

<div class="field">
	<%= f.label :name, 'Location-Time Zone' %>
	<br />
	<%= f.text_field :location %>
</div>

<div class="field">
	<%= f.label :name, 'Address' %>
	<br />
	<%= f.text_field :address %>
</div>

<div class="field">
	<%= f.label :name, 'Sex' %>
	<br />
	<%= f.text_field :sex %>
</div>
<div class="field">
	<%= f.label :age %>
	<br />
	<%= f.number_field :age %>
</div>
<div class="field">
	<%= f.label :phone %>
	<br />
	<%= f.text_field :phone %>
</div>
<div class="field">
	<%= f.label :name, 'Dr. Name'%>
	<br />
	<%= f.text_field :dr_name %>
</div>
<div class="field">
	<%= f.label :diagnosis %>
	<br />
	<%= f.text_field :diagnosis %>
</div>
<div class="field">
	<%= f.label :name, 'Received at Home' %>
	<br />
	<%= f.text_field :rec_at_home %>
</div>
<div class="field">
	<%= f.label :name, 'Started Injections' %>
	<br />
	<%= f.text_field :started_injections %>
</div>

<div class="field">
	<%= f.label :notes %>
	<br />
	<%= f.text_area :notes, :size => "40x10" %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Clients Administration</h1>

<table>
  <tr>
  	<th></th>
    <th>Name</th>
    <th>DoB</th>
    <th>Location</th>
    <th>Sex</th>
    <th>Age</th>   
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
  	<td><%= link_to "New Session", {:controller => 'clients', :action => "opening", :id => client } %></td>
    <td><%= client.name %></td>
    <td><%= client.dob %></td>
    <td><%= client.location %></td>
    <td><%= client.sex %></td>
    <td><%= client.age %></td>
      
    
    <td><%= link_to "Summary", {:controller => 'clients', :action => "opening", :id => client } %></td>
<!--   <td><%= link_to 'Details', client %></td> -->

    <td><%= link_to 'Edit', edit_client_path(client) %></td>    
    <td><%= button_to 'Remove Client', client, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

</br>

<%= link_to "Client Sessions", {:controller => 'sessions'} %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/opening.html.erb
<h1> New Session Documentation </h1>

<%= link_to 'Begin New Session', sessions_path %>

<!-- 		<%= link_to "1. Opening", {:controller => 'clients', :action => "index" } %>   -->

<div class="demo">
	<div class="demo">
		<div id="accordion">
			<h3><a href="#section1">Basic Patient Infomation</a></h3>
			<div>
				<p>
					<b>Name:</b>
					<%= @client.name %>
				</p>
				<p>
					<b>DoB:</b>
					<%= @client.dob %>
				</p>				
				<p>
					<b>Location-Time Zone:</b>
					<%= @client.location %>
				</p>
				<p>
					<b>Address:</b>
					<%= @client.address %>
				</p>
				<p>
					<b>Sex:</b>
					<%= @client.sex %>
				</p>
				<p>
					<b>Age:</b>
					<%= @client.age %>
				</p>
				<p>
					<b>Phone:</b>
					<%= @client.phone %>
				</p>
			</div>
			
			<h3><a href="#section2">Details</a></h3>
			<div>
				<p>
					<b>Referral Date:</b>
					<%= @client.referral_date %>
				</p>
				<p>
					<b>Enroll Date:</b>
					<%= @client.enrolldate %>
				</p>
				<p>
					<b>Started Injections:</b>
					<%= @client.started_injections %>
				</p>
				<p>
					<b>Receive Acthar at Home:</b>
					<%= @client.rec_at_home %>
				</p>
				<p>
					<b>Dr. Name:</b>
					<%= @client.dr_name %>
				</p>				
				<p>
					<b>Diagnosis:</b>
					<%= @client.diagnosis %>
				</p>			
			</div>			
			<h3><a href="#section3">Overview Notes</a></h3>
			<div>
				<p>
					<%= @client.notes %>
				</p>
			</div>

		</div>
	</div>

app/views/clients/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<b>Name:</b>
	<%= @client.name %>
</p>
<p>
	<b>Dob:</b>
	<%= @client.dob %>
</p>
<p>
	<b>referral Date:</b>
	<%= @client.referral_date %>
</p>
<p>
	<b>Enroll Date:</b>
	<%= @client.enrolldate %>
</p>
<p>
	<b>Started Injections:</b>
	<%= @client.started_injections %>
</p>
<p>
	<b>Receive Acthar at Home:</b>
	<%= @client.rec_at_home %>
</p>
<p>
	<b>Dr. Name:</b>
	<%= @client.dr_name %>
</p>
<p>
	<b>Diagnosis:</b>
	<%= @client.diagnosis %>
</p>
<p>
	<b>Location-Time Zone:</b>
	<%= @client.location %>
</p>
<p>
	<b>Address:</b>
	<%= @client.address %>
</p>
<p>
	<b>Sex:</b>
	<%= @client.sex %>
</p>
<p>
	<b>Age:</b>
	<%= @client.age %>
</p>
<p>
	<b>Phone:</b>
	<%= @client.phone %>
</p>
<p>
	<b>Notes:</b>
	<%= @client.notes %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>