config/routes.rb
Hcs::Application.routes.draw do

  resources :notes

  resources :sessions do
    resources :notes
  end

  resources :clients do
    resources :sessions
  end

  resources :users

  get "users/new"

  match '/opening', :to => 'clients#opening'

  match '/signup', :to => 'users#new'

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/commonissues', :to => 'pages#commonissues'
  match '/barriers', :to => 'pages#barriers'
  match '/opening', :to => 'pages#opening'
  match '/positive', :to => 'pages#positive'
  match '/closing', :to => 'pages#closing'

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "About", about_path %>
			</li>
			<li>
				<%= link_to "Contact", contact_path %>
			</li>
			<!--<li><a href="http://news.railstutorial.org/">News</a></li>-->
			<!--<li><a href="http://www.railstutorial.org/">RailsTutorial</a></li>-->
			<li>
				<a href="http://www.humancaresystems.com/">Human Care Systems</a>
			</li>
			<li>
				<a href="http://www.obliquevision.org/">Obliquevision</a>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<% logo = image_tag("hcs_logo.gif", :alt=> "SampleApp", :class=> "round")%>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "Home", root_path %>
			</li>

			<li>
				<%= link_to "Clients", clients_path %>
			</li>
			<li>
				<%= link_to "About", about_path %>
			</li>
			<li>
				<%= link_to "Help", help_path %>
			</li>
			<li>
				<%= link_to "Sign in", '#'%>
			</li>
			<!--		<button>
			Click me </button>  -->
		</ul>
	</nav>

</header>

app/views/layouts/_progress.html.erb
<div>
	<nav class="round">
		<ul>
			<li>
				<!--			<%= link_to '1. Opening', clients_path %> -->
				<!-- 		<%= link_to "1. Opening", {:controller => 'clients', :action => "index" } %>   -->
			</li>
			
			<li>
				<%= link_to "1. Client Hisory", clients_path %>
			</li>					
			<li>
				<%= link_to "2. Assesment", {:controller => 'pages', :action => "commonissues" } %>
			</li>
			
			<li>
				<%= button_to "3. Barriers to Progress - Reference", {:controller => 'pages', :action => "barriers" } %>
			</li>
			<li>
				<%= button_to "4. Closing-Scheduling", {:controller => 'pages', :action => 'closing' } %>
			</li>
		</ul>
	</nav>
	<br />
</div>

app/views/layouts/_stylesheets.html.erb
<!--[ifltIE9]>
<scriptsrc="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media=> 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media=> 'print' %> <!--[ifltIE8]><%=stylesheet_link_tag 'blueprint/ie'%><![endif]-->
<%= stylesheet_link_tag 'custom', :media=> 'screen' %>
<%= stylesheet_link_tag 'jquery-ui', :media=> 'screen' %>
<%= javascript_include_tag  "jquery" %>
<%= javascript_include_tag  "jquery-ui" %>
<%= javascript_include_tag "jquery-rails.js" %> 

app/views/layouts/application.html.erb
<!DOCTYPEhtml>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag%>
			
    <%= javascript_include_tag :defaults %>
   	
		<%= render 'layouts/stylesheets' %> <script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				$("button").click(function() {
					$(this).hide();
				});
			});
			$(function() {
				$("#accordion").accordion({
					fillSpace : true
				});
			});
			$(function() {
				$("#accordionResizer").resizable({
					minHeight : 140,
					resize : function() {
						$("#accordion").accordion("resize");
					}
				});
			});
			
			$(function() {
				$("#check").button();
				$("#format").buttonset();
			});
			$(function() {
				$("#radio").buttonset();
			});

		</script>
	</head>
	</head>
	<body>
		<div class= "container" >
			<%= render 'layouts/header' %>
			<%= render 'layouts/progress' %>
			<section class="round">
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>